"""empty message

Revision ID: f9a469fc4388
Revises: b711bd8ca6c7
Create Date: 2022-08-03 20:03:21.585669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a469fc4388'
down_revision = 'b711bd8ca6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=60), nullable=False),
    sa.Column('contains', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=150), nullable=False),
    sa.Column('price', sa.String(length=150), nullable=False),
    sa.Column('qty', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit')
    )
    op.alter_column('user', 'firstName',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('user', 'lastName',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('user', 'mail',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('user', 'mail',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('user', 'lastName',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('user', 'firstName',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.drop_table('product')
    # ### end Alembic commands ###
