"""empty message

Revision ID: fb4f5aade561
Revises: 0e99a78ac9ff
Create Date: 2022-08-19 15:13:28.699716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4f5aade561'
down_revision = '0e99a78ac9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('unit', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'unit')
    # ### end Alembic commands ###
